name: Nightly
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  publish_nightly:
    uses: rancher-sandbox/highlander-reusable-workflows/.github/workflows/operator-with-latest-rancher-build.yaml@main
    with:
      operator_name: eks-operator
      rancher_ref: release/v2.8
      operator_commit: ${{ github.sha }}
