name: Update EKS operator in rancher/rancher
on:
  workflow_dispatch:
    inputs:
      rancher_ref:
        description: "Submit PR against the following rancher/rancher branch (e.g. release/v2.7)"
        default: "release/v2.8"
      new_eks:
        description: "New EKS operator version (e.g. 1.1.0-rc2), don't include the 'v'"
        required: true
        default: ""
jobs:
  update-rancher-dep:
    uses: rancher-sandbox/highlander-reusable-workflows/.github/workflows/update-rancher-dep.yaml@main
    with:
      rancher_ref: ${{ github.event.inputs.rancher_ref }}
      new_operator_version: ${{ github.event.inputs.new_eks }}
      operator_repo: github.com/rancher/eks-operator
    secrets:
      token: ${{secrets.CI_BOT_TOKEN}}
